#!/usr/bin/env python3
"""
Event-guided RGB enhancement for drone detection.

This script trains a lightweight residual U-Net that takes synchronized:
- RGB image (3 channels)
- Event image (1 channel)
and predicts an enhanced RGB image.

The model learns:
  enhanced_rgb = rgb + residual

Data assumption:
The dataset root contains preprocessed sequence folders generated by
scripts/preprocessing/preprocess_fred_dataset.py, for example:
  data/preprocessed/preprocessed_fred_1/
  data/preprocessed/preprocessed_fred_10/

Each sequence folder should contain paired manifests:
  paired/manifest_train.csv
  paired/manifest_val.csv
  paired/manifest_test.csv

The manifest rows are expected to have at least:
  rgb_image,event_image
as paths relative to the sequence folder.
"""

from __future__ import annotations

import argparse
import csv
import json
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchvision.transforms.functional import pil_to_tensor as tv_pil_to_tensor
from torchvision.utils import save_image


@dataclass(frozen=True)
class PairRecord:
    seq_root: Path
    rgb_path: Path
    event_path: Path
    split: str


def set_seed(seed: int) -> None:
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


class PairManifestDataset(Dataset):
    def __init__(self, records: list[PairRecord], image_size: int = 512) -> None:
        self.records = records
        self.image_size = image_size

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, index: int) -> dict[str, torch.Tensor]:
        item = self.records[index]

        rgb = Image.open(item.rgb_path).convert("RGB")
        event = Image.open(item.event_path).convert("L")

        rgb = rgb.resize((self.image_size, self.image_size), Image.Resampling.BILINEAR)
        event = event.resize((self.image_size, self.image_size), Image.Resampling.BILINEAR)

        rgb_t = pil_to_tensor(rgb)
        event_t = pil_to_tensor(event)

        return {
            "rgb": rgb_t,
            "event": event_t,
        }


def pil_to_tensor(image: Image.Image) -> torch.Tensor:
    # Convert PIL to float tensor in [0, 1], shape CxHxW.
    return tv_pil_to_tensor(image).float() / 255.0


def discover_records(data_root: Path, split: str) -> list[PairRecord]:
    records: list[PairRecord] = []
    seq_dirs = sorted(p for p in data_root.glob("preprocessed_fred_*") if p.is_dir())

    for seq_dir in seq_dirs:
        manifest_path = seq_dir / "paired" / f"manifest_{split}.csv"
        if not manifest_path.is_file():
            continue

        with manifest_path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                rgb_rel = row.get("rgb_image", "").strip()
                event_rel = row.get("event_image", "").strip()
                if not rgb_rel or not event_rel:
                    continue

                rgb_path = seq_dir / rgb_rel
                event_path = seq_dir / event_rel
                if not rgb_path.is_file() or not event_path.is_file():
                    continue

                records.append(
                    PairRecord(
                        seq_root=seq_dir,
                        rgb_path=rgb_path,
                        event_path=event_path,
                        split=split,
                    )
                )

    return records


class ConvBlock(nn.Module):
    def __init__(self, in_ch: int, out_ch: int) -> None:
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, kernel_size=3, padding=1),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.block(x)


class Down(nn.Module):
    def __init__(self, in_ch: int, out_ch: int) -> None:
        super().__init__()
        self.conv = ConvBlock(in_ch, out_ch)
        self.pool = nn.MaxPool2d(2)

    def forward(self, x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        feat = self.conv(x)
        down = self.pool(feat)
        return feat, down


class Up(nn.Module):
    def __init__(self, in_ch: int, skip_ch: int, out_ch: int) -> None:
        super().__init__()
        self.up = nn.Upsample(scale_factor=2, mode="bilinear", align_corners=False)
        self.conv = ConvBlock(in_ch + skip_ch, out_ch)

    def forward(self, x: torch.Tensor, skip: torch.Tensor) -> torch.Tensor:
        x = self.up(x)
        if x.shape[-2:] != skip.shape[-2:]:
            x = F.interpolate(x, size=skip.shape[-2:], mode="bilinear", align_corners=False)
        x = torch.cat([x, skip], dim=1)
        return self.conv(x)


class EventGuidedEnhancer(nn.Module):
    """Lightweight residual U-Net, input 4 channels (RGB + Event), output 3 channels residual."""

    def __init__(self, base_channels: int = 32, residual_scale: float = 0.2) -> None:
        super().__init__()
        self.residual_scale = residual_scale

        self.enc1 = Down(4, base_channels)
        self.enc2 = Down(base_channels, base_channels * 2)
        self.enc3 = Down(base_channels * 2, base_channels * 4)

        self.bottleneck = ConvBlock(base_channels * 4, base_channels * 8)

        self.dec3 = Up(base_channels * 8, base_channels * 4, base_channels * 4)
        self.dec2 = Up(base_channels * 4, base_channels * 2, base_channels * 2)
        self.dec1 = Up(base_channels * 2, base_channels, base_channels)

        self.out_conv = nn.Conv2d(base_channels, 3, kernel_size=1)

    def forward(self, rgb: torch.Tensor, event: torch.Tensor) -> dict[str, torch.Tensor]:
        x = torch.cat([rgb, event], dim=1)

        s1, x = self.enc1(x)
        s2, x = self.enc2(x)
        s3, x = self.enc3(x)

        x = self.bottleneck(x)

        x = self.dec3(x, s3)
        x = self.dec2(x, s2)
        x = self.dec1(x, s1)

        residual = torch.tanh(self.out_conv(x)) * self.residual_scale
        enhanced = torch.clamp(rgb + residual, 0.0, 1.0)

        return {
            "residual": residual,
            "enhanced": enhanced,
        }


class WeightedEdgeLoss(nn.Module):
    """Encourages sharper gradients where event intensity is high."""

    def __init__(self, eps: float = 1e-6) -> None:
        super().__init__()
        self.eps = eps
        gx = torch.tensor([[-1.0, 0.0, 1.0], [-2.0, 0.0, 2.0], [-1.0, 0.0, 1.0]], dtype=torch.float32)
        gy = torch.tensor([[-1.0, -2.0, -1.0], [0.0, 0.0, 0.0], [1.0, 2.0, 1.0]], dtype=torch.float32)
        self.register_buffer("gx", gx.view(1, 1, 3, 3))
        self.register_buffer("gy", gy.view(1, 1, 3, 3))

    def _grad_mag(self, x: torch.Tensor) -> torch.Tensor:
        # Average over channels before Sobel to get luminance-like gradient.
        gray = x.mean(dim=1, keepdim=True)
        dx = F.conv2d(gray, self.gx, padding=1)
        dy = F.conv2d(gray, self.gy, padding=1)
        return torch.sqrt(dx * dx + dy * dy + self.eps)

    def forward(self, enhanced: torch.Tensor, rgb: torch.Tensor, event: torch.Tensor) -> torch.Tensor:
        grad_e = self._grad_mag(enhanced)
        grad_rgb = self._grad_mag(rgb)

        # Positive margin on event-active regions to boost edges.
        weight = torch.clamp(event, 0.0, 1.0)
        target_margin = 0.05
        gain = grad_e - grad_rgb
        penalty = F.relu(target_margin - gain)
        return (weight * penalty).mean()


def compute_losses(
    enhanced: torch.Tensor,
    residual: torch.Tensor,
    rgb: torch.Tensor,
    event: torch.Tensor,
    edge_loss_fn: WeightedEdgeLoss,
    w_recon: float,
    w_edge: float,
    w_event_residual: float,
    event_residual_margin: float,
) -> tuple[torch.Tensor, dict[str, float]]:
    l_recon = F.l1_loss(enhanced, rgb)
    l_edge = edge_loss_fn(enhanced, rgb, event)

    # Encourage non-trivial residual where event activity is high.
    residual_mag = residual.abs().mean(dim=1, keepdim=True)
    residual_penalty = F.relu(event_residual_margin - residual_mag)
    l_event_residual = (torch.clamp(event, 0.0, 1.0) * residual_penalty).mean()

    total = w_recon * l_recon + w_edge * l_edge + w_event_residual * l_event_residual
    stats = {
        "loss_total": float(total.detach().cpu()),
        "loss_recon": float(l_recon.detach().cpu()),
        "loss_edge": float(l_edge.detach().cpu()),
        "loss_event_residual": float(l_event_residual.detach().cpu()),
    }
    return total, stats


def run_epoch(
    model: EventGuidedEnhancer,
    loader: DataLoader,
    device: torch.device,
    optimizer: torch.optim.Optimizer | None,
    scaler: torch.amp.GradScaler | None,
    use_amp: bool,
    edge_loss_fn: WeightedEdgeLoss,
    w_recon: float,
    w_edge: float,
    w_event_residual: float,
    event_residual_margin: float,
    max_batches: int | None = None,
) -> dict[str, float]:
    training = optimizer is not None
    model.train(training)

    totals = {"loss_total": 0.0, "loss_recon": 0.0, "loss_edge": 0.0, "loss_event_residual": 0.0}
    count = 0

    for batch_idx, batch in enumerate(loader):
        if max_batches is not None and batch_idx >= max_batches:
            break

        rgb = batch["rgb"].to(device, non_blocking=True)
        event = batch["event"].to(device, non_blocking=True)

        with torch.set_grad_enabled(training):
            with torch.autocast(device_type=device.type, enabled=use_amp):
                out = model(rgb, event)
                loss, stats = compute_losses(
                    enhanced=out["enhanced"],
                    residual=out["residual"],
                    rgb=rgb,
                    event=event,
                    edge_loss_fn=edge_loss_fn,
                    w_recon=w_recon,
                    w_edge=w_edge,
                    w_event_residual=w_event_residual,
                    event_residual_margin=event_residual_margin,
                )

            if training:
                assert optimizer is not None
                optimizer.zero_grad(set_to_none=True)
                if scaler is not None:
                    scaler.scale(loss).backward()
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    loss.backward()
                    optimizer.step()

        for k in totals:
            totals[k] += stats[k]
        count += 1

    if count == 0:
        return totals

    for k in totals:
        totals[k] /= count
    return totals


def save_checkpoint(path: Path, model: nn.Module, optimizer: torch.optim.Optimizer, epoch: int, cfg: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    # Keep config JSON-safe so checkpoints remain compatible with stricter torch.load defaults.
    cfg_safe = {}
    for key, value in cfg.items():
        if isinstance(value, Path):
            cfg_safe[key] = str(value)
        else:
            cfg_safe[key] = value

    torch.save(
        {
            "epoch": epoch,
            "model": model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "config": cfg_safe,
        },
        path,
    )


def train(args: argparse.Namespace) -> None:
    set_seed(args.seed)

    data_root = args.data_root.resolve()
    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    train_records = discover_records(data_root, "train")
    val_records = discover_records(data_root, "val")

    if args.limit_train_records is not None:
        limit = max(1, args.limit_train_records)
        train_records = train_records[:limit]

    if args.limit_val_records is not None and val_records:
        limit = max(1, args.limit_val_records)
        val_records = val_records[:limit]

    if not train_records:
        raise RuntimeError(f"No training records found under {data_root}")

    train_ds = PairManifestDataset(train_records, image_size=args.image_size)
    val_ds = PairManifestDataset(val_records, image_size=args.image_size) if val_records else None

    device = torch.device("cuda" if torch.cuda.is_available() and not args.cpu else "cpu")
    pin_memory = device.type == "cuda"

    train_loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=pin_memory,
    )

    val_loader = None
    if val_ds is not None:
        val_loader = DataLoader(
            val_ds,
            batch_size=args.batch_size,
            shuffle=False,
            num_workers=args.num_workers,
            pin_memory=pin_memory,
        )

    model = EventGuidedEnhancer(base_channels=args.base_channels, residual_scale=args.residual_scale).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    edge_loss_fn = WeightedEdgeLoss().to(device)
    use_amp = device.type == "cuda" and not args.no_amp
    scaler = torch.amp.GradScaler(device=device.type, enabled=use_amp)

    cfg = vars(args).copy()
    history: list[dict] = []

    for epoch in range(1, args.epochs + 1):
        train_stats = run_epoch(
            model,
            train_loader,
            device,
            optimizer,
            scaler=scaler,
            use_amp=use_amp,
            edge_loss_fn=edge_loss_fn,
            w_recon=args.w_recon,
            w_edge=args.w_edge,
            w_event_residual=args.w_event_residual,
            event_residual_margin=args.event_residual_margin,
            max_batches=args.max_train_batches,
        )

        row = {"epoch": epoch, "train": train_stats}

        if val_loader is not None:
            with torch.no_grad():
                val_stats = run_epoch(
                    model,
                    val_loader,
                    device,
                    optimizer=None,
                    scaler=None,
                    use_amp=use_amp,
                    edge_loss_fn=edge_loss_fn,
                    w_recon=args.w_recon,
                    w_edge=args.w_edge,
                    w_event_residual=args.w_event_residual,
                    event_residual_margin=args.event_residual_margin,
                    max_batches=args.max_val_batches,
                )
            row["val"] = val_stats
            print(
                f"Epoch {epoch:03d} | train total={train_stats['loss_total']:.4f} "
                f"val total={val_stats['loss_total']:.4f}"
            )
        else:
            print(f"Epoch {epoch:03d} | train total={train_stats['loss_total']:.4f}")

        history.append(row)

        if epoch % args.save_every == 0 or epoch == args.epochs:
            ckpt_path = out_dir / "checkpoints" / f"enhancer_epoch_{epoch:03d}.pt"
            save_checkpoint(ckpt_path, model, optimizer, epoch, cfg)

    (out_dir / "train_history.json").write_text(json.dumps(history, indent=2), encoding="utf-8")


@torch.no_grad()
def infer(args: argparse.Namespace) -> None:
    device = torch.device("cuda" if torch.cuda.is_available() and not args.cpu else "cpu")

    # Local training checkpoints are trusted in this workflow; weights_only=False restores full dict.
    ckpt = torch.load(args.checkpoint, map_location=device, weights_only=False)
    cfg = ckpt.get("config", {})

    model = EventGuidedEnhancer(
        base_channels=int(cfg.get("base_channels", 32)),
        residual_scale=float(cfg.get("residual_scale", 0.2)),
    ).to(device)
    model.load_state_dict(ckpt["model"])
    model.eval()

    records = discover_records(args.data_root.resolve(), args.split)
    if not records:
        raise RuntimeError(f"No records found for split={args.split}")

    if args.max_records is not None:
        records = records[: max(1, args.max_records)]

    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    for i, rec in enumerate(records):
        rgb = Image.open(rec.rgb_path).convert("RGB")
        event = Image.open(rec.event_path).convert("L")

        orig_size = rgb.size
        rgb_r = rgb.resize((args.image_size, args.image_size), Image.Resampling.BILINEAR)
        event_r = event.resize((args.image_size, args.image_size), Image.Resampling.BILINEAR)

        rgb_t = pil_to_tensor(rgb_r).unsqueeze(0).to(device)
        event_t = pil_to_tensor(event_r).unsqueeze(0).to(device)

        out = model(rgb_t, event_t)
        residual = out["residual"]
        enhanced_t = torch.clamp(rgb_t + residual * args.residual_gain, 0.0, 1.0)
        enhanced = enhanced_t.squeeze(0).cpu()

        enh_pil = tensor_to_pil(enhanced).resize(orig_size, Image.Resampling.BILINEAR)

        # Prefix with sequence name to avoid collisions across folders.
        name = f"{rec.seq_root.name}_{rec.rgb_path.stem}_enhanced.png"
        enh_pil.save(out_dir / name)

        if args.save_triplets:
            rgb_p = tensor_to_pil(rgb_t.squeeze(0).cpu())
            event_rgb = tensor_to_pil(event_t.repeat(1, 3, 1, 1).squeeze(0).cpu())
            triplet = torch.cat(
                [
                    pil_to_tensor(rgb_p),
                    pil_to_tensor(event_rgb),
                    pil_to_tensor(tensor_to_pil(enhanced)),
                ],
                dim=2,
            )
            save_image(triplet, out_dir / f"{rec.seq_root.name}_{rec.rgb_path.stem}_triplet.png")

        if (i + 1) % 100 == 0:
            print(f"Processed {i + 1}/{len(records)}")


def tensor_to_pil(t: torch.Tensor) -> Image.Image:
    t = torch.clamp(t, 0.0, 1.0)
    t = (t * 255.0).byte().permute(1, 2, 0).contiguous().numpy()
    if t.shape[2] == 1:
        return Image.fromarray(t[:, :, 0], mode="L")
    return Image.fromarray(t, mode="RGB")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train/infer event-guided RGB enhancement model.")
    sub = parser.add_subparsers(dest="command", required=True)

    train_p = sub.add_parser("train", help="Train enhancer.")
    train_p.add_argument("--data-root", type=Path, default=Path("data/preprocessed"))
    train_p.add_argument("--out-dir", type=Path, default=Path("artifacts/enhancer"))
    train_p.add_argument("--epochs", type=int, default=30)
    train_p.add_argument("--batch-size", type=int, default=2)
    train_p.add_argument("--num-workers", type=int, default=4)
    train_p.add_argument("--image-size", type=int, default=384)
    train_p.add_argument("--lr", type=float, default=1e-3)
    train_p.add_argument("--weight-decay", type=float, default=1e-4)
    train_p.add_argument("--base-channels", type=int, default=32)
    train_p.add_argument("--residual-scale", type=float, default=0.2)
    train_p.add_argument("--w-recon", type=float, default=1.0)
    train_p.add_argument("--w-edge", type=float, default=0.5)
    train_p.add_argument(
        "--w-event-residual",
        type=float,
        default=0.0,
        help="Weight for encouraging non-trivial residuals in event-active regions.",
    )
    train_p.add_argument(
        "--event-residual-margin",
        type=float,
        default=0.02,
        help="Target minimum residual magnitude in event-active regions.",
    )
    train_p.add_argument("--save-every", type=int, default=5)
    train_p.add_argument("--seed", type=int, default=42)
    train_p.add_argument("--no-amp", action="store_true", help="Disable mixed precision on CUDA.")
    train_p.add_argument(
        "--max-train-batches",
        type=int,
        default=None,
        help="Limit number of train batches per epoch (for quick pilot runs).",
    )
    train_p.add_argument(
        "--max-val-batches",
        type=int,
        default=None,
        help="Limit number of val batches per epoch (for quick pilot runs).",
    )
    train_p.add_argument(
        "--limit-train-records",
        type=int,
        default=None,
        help="Use only first N train records (for quick pilot runs).",
    )
    train_p.add_argument(
        "--limit-val-records",
        type=int,
        default=None,
        help="Use only first N val records (for quick pilot runs).",
    )
    train_p.add_argument("--cpu", action="store_true")

    infer_p = sub.add_parser("infer", help="Run inference and save enhanced images.")
    infer_p.add_argument("--data-root", type=Path, default=Path("data/preprocessed"))
    infer_p.add_argument("--checkpoint", type=Path, required=True)
    infer_p.add_argument("--out-dir", type=Path, default=Path("artifacts/enhancer_infer"))
    infer_p.add_argument("--split", choices=["train", "val", "test"], default="test")
    infer_p.add_argument("--image-size", type=int, default=512)
    infer_p.add_argument(
        "--max-records",
        type=int,
        default=None,
        help="Process only first N records for quick sampling.",
    )
    infer_p.add_argument(
        "--residual-gain",
        type=float,
        default=1.0,
        help="Scale residual at inference for visualization (1.0 = normal).",
    )
    infer_p.add_argument("--save-triplets", action="store_true")
    infer_p.add_argument("--cpu", action="store_true")

    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.command == "train":
        train(args)
    elif args.command == "infer":
        infer(args)
    else:
        raise ValueError(f"Unknown command: {args.command}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
